# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negot', '0007_auto_20160409_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='avg_price',
            field=models.FloatField(default=-1, max_length=50),
            preserve_default=False,
        ),
    ]
