# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negot', '0008_availability_avg_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='neighbourhood',
            field=models.CharField(default='empty', max_length=254),
            preserve_default=False,
        ),
    ]
